name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: mix check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: team-alembic/staple-actions/actions/install-elixir@main
      - uses: team-alembic/staple-actions/actions/mix-check@main
        with:
          mix-env: test
